### PR TITLE
add Shared element transition from gridList to ViewerFragment

### PR DESCRIPTION
**Pull request by Ezike**
Thought a shared element transition would be cool 😎. sadly, if the user swipes images with the viewpager and clicks back, the transition returns to the image that was first clicked.

Do share your thoughts 🙂 @msasikanth

### CODE REVIEW

**Comment by msasikanth** [comment]
Hey Ezike, thanks for the PR. But I am already working on this feature. I am trying to fix the position of the return shared element transition efficiently, so I would probably commit this feature today or tomorrow hopefully.

BTW I would suggest using an Event and EventObserver in future instead of SingleLiveEvent

ref : https://medium.com/androiddevelopers/livedata-with-snackbar-navigation-and-other-events-the-singleliveevent-case-ac2622673150

**Comment by Ezike** [comment]
OK that's cool. Looking forward to seeing those features in the app.

**Comment by msasikanth** [comment]
This is the ViewModel SavedState implementation incase you are interested.

https://github.com/msasikanth/Gaze/commit/ab760fe335f5f0912dda04138f7dd7bd07984b44

**Comment by Ezike** [comment]
Yeah thanks for the tg. I'm currently going through it. Although one of my issues with it was injecting the savedStateVM and using assisted inject. It didn't feel elegant enough

**Comment by msasikanth** [comment]
Unfortunately we need it there, if you’re not using dagger and don’t have any other constructor parameters other than SavedStateHandle you can use SavedStateViewModelFactory in 

```
ViewModelProviders.of(this, SavedStateViewModelFactory(application, this)).get(MainViewModel::class.java)
```

or if you are using latest alpha version of activity and fragment they have default SavedStateViewModelFactory when you are requesting ViewModel.

AssitedInject in generally is really useful dynamic content where activity/fragment provides something into ViewModel at runtime.

**Comment by Ezike** [comment]
Okay nice. Why didn't you just update to the latest version of activity and
fragment if they have default SavedStateViewModelFactory. What are the
challenges with using that. Also, why aren't you using dagger android?

**Comment by Ezike** [comment]
Also i'm unable to build the project
`constructor MainViewModel in class MainViewModel cannot be applied to given types;
    return new MainViewModel(aPodRepository);
           ^
  required: APodRepository,SavedStateHandle
  found: APodRepository
  reason: actual and formal argument lists differ in length`

**Comment by msasikanth** [comment]
> Okay nice. Why didn't you just update to the latest version of activity and fragment if they have default SavedStateViewModelFactory. What are the challenges with using that. Also, why aren't you using dagger android?
> […](#)

I may not have added the latest alpha of activity and fragment explicitly, but I think they are added when I used appcompat dependency I am not sure. But those are present in the project. Even if the SavedStateViewModelFactory is default I cannot just use it since I have other constructor params for the ViewModel, so I have to extend AbstractSavedStateViewModelFactory and use AssistedInject to inject SavedStateHandle into ViewModel.

For this app use case dagger is enough, I don't know why I would need dagger android. Unless just to use DaggerAppCompatActivity and DaggerFragment. I just want to have simple implementation.

**Comment by msasikanth** [comment]
> Also i'm unable to build the project
> `constructor MainViewModel in class MainViewModel cannot be applied to given types; return new MainViewModel(aPodRepository); ^ required: APodRepository,SavedStateHandle found: APodRepository reason: actual and formal argument lists differ in length`

Check README file, you have to provide apiKey in local.properties file, like 
`apiKey = "your_api_key_here"` in quotes

**Comment by Ezike** [comment]
I have an apikey already

**Comment by msasikanth** [comment]
Can you screenshot the local.properties file? 🤔 

Also dagger is throwing build errors?

**Comment by Ezike** [comment]
`## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Thu Aug 29 09:39:43 WAT 2019
sdk.dir=/Users/eziketobenna/Library/Android/sdk
apiKey = "v5VjcJOgwINhKPaQi9qf9XbqcD1SZDJzpVKQV3AO"`
this is it. the error is in the generated class for mainViewmodel

**Comment by msasikanth** [comment]
Have you tried clean build? I am not having any trouble setting up a new project 🤔

**Pull request closed without merging**
